#!/bin/bash

case "${1}" in
  configure)
    echo "Enabling & starting DHCP and PXE boot services"
    
    cp /etc/exports /etc/exports.old
    echo "/etc/sage-utils/dhcp-pxe/nfs *(rw,fsid=0,no_subtree_check,no_auth_nlm,insecure,no_root_squash)" >> /etc/exports
	
    cp /etc/dnsmasq.conf /etc/dnsmasq.conf.old
    cp /etc/sage-utils/dhcp-pxe/dnsmasq.conf /etc/dnsmasq.conf

    exportfs -ra
    systemctl restart dnsmasq
    systemctl restart rpcbind
    systemctl restart nfs-kernel-server
    ;;
esac
