#!/bin/bash

rm -r /media/rpi/sage-utils/dhcp-pxe/

rm /etc/exports
mv /etc/exports.old /etc/exports

rm /etc/dnsmasq.conf
mv /etc/dnsmasq.conf.old /etc/dnsmasq.conf

exportfs -ra
systemctl restart dnsmasq || true
systemctl restart rpcbind || true
systemctl restart nfs-kernel-server || true
